#!/bin/bash

choice=4

echo "1. Bash"
echo "2. Scripting"
echo "3. Tutorial"
echo -n "Enter your choice [1,2 or 3]?"

while [ $choice -eq 4 ]; do

read choice

if [ $choice -eq 1 ]; then
  echo "you chose $choice Bash"
else

    if [ $choice -eq 2 ]; then
      echo "you chose $choice Scripting"
    else
      if [ $choice -eq 3 ]; then
        echo "you chose $choice Tutorial"
      else
        echo "Please make a choice between 1-3"
        echo "1. Bash"
        echo "2. Scripting"
        echo "3. Tutorial"
        echo -n "Enter your choice [1,2 or 3]?"
        choice=4
      fi
    fi
fi
done
